### ISSUE TITLE
Improve Graph Rendering

### ISSUE THREAD

**Issue by RamonMeffert** [RamonMeffert/elm-gossip#15]
- Consider rendering the first N agents in a circle to improve quality of rendered graph
- Look at how GraphViz renders graph (probably very hard)
- At the very least, make sure nodes do not overlap

**Comment by m4lvin** [comment]
Some examples that are currently rendered with overlapping nodes:
- `Ab B bCd D dE` (a "double bush")
- `Ab B bC D E F` (some disconnected nodes)
- `A B abC abD abE abF` (some nodes with the same links)

**Comment by RamonMeffert** [comment]
The library I'm using to render the graph, [elm-visualization](https://package.elm-lang.org/packages/gampleman/elm-visualization/latest/), just received a major update. Notably, they've added support for collision detection in force-directed graphs. This will solve this problem! I'll update to this new version when I find some time, hopefully soon.

**Comment by RamonMeffert** [comment]
Should be better now!
